### ISSUE TITLE
Font generator without upload

### ISSUE THREAD

**Issue by tomasmalio** [ambroisemaupate/webfont-generator#2]
Hi,
I'm trying to make a module to integrate to different kind of platforms that have multiple fonts. My idea is to create a script with receive the directory and filename and then automatically generate the eot, woff, svg font files.
It's any possibility to change your own code to transform to this, so there's no need to upload files?
Thanks for your time and congratulations of your work.
Talk you soon,
Tom

**Comment by ambroisemaupate** [comment]
Hi @tomasmalio 

You can already use the webfont generator without the “App”, just using its components without the UI. 

https://github.com/ambroisemaupate/webfont-generator/blob/master/src/App.php#L120

```php
$fs = new Filesystem();
$subsetLatin = true; // Add option to subset or not
$filesToConvert = []; // fetch your native font file with your own method.
$font = new WebFont(
    $fs,
    $this->getFontConverters(),
    $this->getFontSubsetter(),
    $subsetRanges // configure your subset range in a config file instead of UI form
);
/** @var File $file */
foreach ($filesToConvert as $file) {
    $font->addFontFile($file);
}
if ($subsetLatin === true) {
    $font->subsetAndConvert();
} else {
    $font->convert();
}
$zipFile = $font->getZipFile();
```

For example, you can create a CLI tool that take a file path input and save the ZIP file elsewhere…

**Comment by tomasmalio** [comment]
Hi @ambroisemaupate,
Thanks for your answer. The other things it that I only have Twig installed, I'm creating this platforms without Symphony, so I don't have some of that components to use inside this script.

**Comment by uwecmyersjj** [comment]
Hey @ambroisemaupate, I would love to use this as a standalone script vs doing the browser upload, etc.

Is there any format of the script that can be used as just a single PHP class vs having Docker and Symphony installed?

**Comment by uwecmyersjj** [comment]
Hey @ambroisemaupate, I would love to use this as a standalone script vs doing the browser upload, etc.

Is there any format of the script that can be used as just a single PHP class vs having Docker and Symphony installed?

**Comment by ambroisemaupate** [comment]
There is no plan to update this lib without Docker because this tool requires external dependencies and binaries:

- fontforge
- ttf2eot
- sfnt2woff
- woff2_compress
- fonttools (pyftsubset)

So you can execute it as mentionned earlier unless you installed these binaries on your host.

Feel free to create a PR for "script" usage if you don't need a browser UX. Or creating a "phar" standalone lib, this way Symfony won't bother you, especially if you want to use excellent symfony/console component for creating a great CLI.
